# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: /#top
    weight: 10
  - name: Créneaux
    url: /#creneaux
    weight: 20
  - name: Evenements à venir
    url: /#evenement
    weight: 30
  - name: Galerie
    url: /#galerie
    weight: 40
  - name: Inscription
    url: /blog/inscription-2024-2025
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
  # - name: Resources
  #   weight: 40
  #   hasChildren: true
  # - parent: Resources
  #   name: Blog
  #   url: blog/
